apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-intro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-intro
  template:
    metadata:
      labels:
        app: react-intro
    spec:
      containers:
      - name: react-intro
        image: apurvbidkar/demo:v3
        ports:
          - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: react-intro
spec:
  selector:
    app: react-intro
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort

